### ISSUE TITLE
Navigation.Header header covers Navigation.Card content

### ISSUE THREAD

**Issue by krivachy** [futurice/pepperoni-app-kit#10]
If the content in Navigation.Card starts at the top, it will be covered by the header.

**Comment by michaelswe** [comment]
Any progress on this?
Any suggested workarounds?

It's a bit quirky to always check if the header is shown and then add an offset to the top.

With this kind of bugs as open issues, I'm getting a little worried that this project will not be around for long. Does anyone use Pepperoni as a base for production apps?

If I had the knowledge I'd try to contribute, of course. But I'm still struggling with learning React/Redux/Immutable.

**Comment by jevakallio** [comment]
@michaelswe this has been now fixed by https://github.com/futurice/pepperoni-app-kit/pull/97/files.

Our apologies for the slow response time. 

The problem isn't that nobody is using Pepperoni in production, quite the opposite! Since the launch, we have been unexpectedly busy building production apps and we haven't had the opportunity to backport the discovered fixes and improvements back to Pepperoni.

Thanks for caring, hope we can support better in the future 🍕 🚀
