### ISSUE TITLE
Navigation Header getTitle never gets invoked

### ISSUE THREAD

**Issue by krivachy** [futurice/pepperoni-app-kit#13]
https://github.com/futurice/pepperoni-app-kit/blob/master/src/modules/navigation/NavigationTabView.js#L25

This line never gets invoked. Currently pepperoni does not support displaying the title for the inner card stack (not the tabs).

**Comment by jevakallio** [comment]
This is fixed by https://github.com/futurice/pepperoni-app-kit/pull/89 (merged as part of https://github.com/futurice/pepperoni-app-kit/pull/95). You can (or MUST) now provide `title` property with each navigation route pushed to the navigation stack, and that title is displayed in the navigation bar.
