### ISSUE TITLE
[npm test] error react-native-auth0\index.js:4 class Auth0

### ISSUE THREAD

**Issue by mika75** [futurice/pepperoni-app-kit#140]
Hello

When i clone project, npm install and npm test

I get this error

Do you have an idea ?

```

\node_modules\react-native-auth0\index.js:4
class Auth0 {
^^^^^

```

Thank

**Comment by Cabanask** [comment]
I have the same error on windows ...

**Comment by tino-junge** [comment]
Hi @mika75 thanks for your interest in Pepperoni 🍕 🚀 ! Are you running react native for ios or android? Your issue seems like the dependencies for Auth0 are not correctly installed. When building the app for iOS you need to install Auth0 pod dependencies first:

```
(cd ios; pod install)
react-native run-ios
```

Let me know if this solves your issue.

**Comment by tino-junge** [comment]
We made Auth0 now optional so pulling from master should resolve your issue now :)
