### ISSUE TITLE
'reasonaboutable' is not a word and just sounds ridiculous

### ISSUE THREAD

**Issue by johanatan** [futurice/pepperoni-app-kit#19]
.

**Comment by jevakallio** [comment]
Yes it is. I [coined it](https://twitter.com/jevakallio/status/638668441327665153) 😃 

In all seriousness, it's a joke. It may or may not be funny, but there we have it. I added a little flair to the docs to make the joke more obvious.

Thank you for caring!

**Comment by johanatan** [comment]
That's certainly better (as at least it doesn't appear to be taking itself seriously as before) but we have several English words that would've sufficed (a thesaurus will turn up many more):
-. understandability
-. comprehensibility
-. explicability 
-. palpability
-. limpidity

**Comment by jevakallio** [comment]
Reasonaboutabilty is a sort of a developer in-joke, making fun of the phrase "easy to reason about" - a meme that is used to justify why people use libraries like React and Redux, the very same libraries we use. Non-limpid state management doesn't really have the same zing to it.

**Comment by johanatan** [comment]
Yes, I'm very familiar with the origin of the phrase-- it comes from the Haskell/statically-typed FP community.

I'm opposed to it in that context as well-- using several [easy] words to describe a property of something is sloppy. It's this realized sloppiness that has motivated people to coin the word "performant". I'd rather see people dig deeper into the lexicon than to invent new words though-- there are plenty of existing from antiquity single-words for both of these concepts.

I think you misread the definition of "limpid"-- it's not non-limpidity we want here but rather limpidity and in my opinion all of the words I mentioned (and at least 10s of others from the dictionary/thesaurus) have a "better zing" to them than "reasonaboutability".

**Comment by frozenxis** [comment]
i like it :)

**Comment by radiovisual** [comment]
FWIW: I use the term "reasonaboutable" all the time. It feels good as a developer to bring meaning to this notion of something that is "kinda-sorta easy to reason about". 😄 

In my mind, a word not being in the dictionary is not enough to disqualify it's usefulness (or legitimacy). We are adding words to the dictionary all the time, because new words are always being invented. I read somewhere that French is the one of the "fastest growing" languages, because they are always adding new words to the dictionary. English is no different.

Words like "Noob", "Pwned", "Guyliner",  "Chillax", "Muggle", and "Fo-Shizzle", simply didn't exist (in a dictionary or otherwise) until suddenly they were invented and people started using them enough to hit the mainstream (which is a path towards an official dictionary entry).

That was just my long way of saying, I think "reasonaboutable" is a great word, and perhaps soon it will get added to a dictionary at the same time that "Crunk" gets added.

😆

**Comment by johanatan** [comment]
In my view, it is merely a display of laziness & an unwillingness to study the existing lexicon (which has far more impressive words to offer).

Further, the aesthetics of this particular word are horrendous-- some combination of suffixes being possible doesn't make them a good idea.

**Comment by jevakallio** [comment]
@johanatan https://youtu.be/7UIE_MRAhEA?t=50

**Comment by johanatan** [comment]
Oh, so Trump is your model? Good luck with that.

**Comment by jevakallio** [comment]
Oh now, why do you have to be so snarkastic?

**Comment by johanatan** [comment]
Sorry. :) Should have thrown in an emoji or two.

**Comment by mannyhappenings** [comment]
I don't really have a problem with coining new words for use, but couldn't people chose something shorter or otherwise leave it?

**Reasonaboutable** is even hard to write(unless you've typed it many times). Also, I don't like learning something new that is not useful in future. We already need to learn a lot on a daily basis.

Please do understand that laziness/efficiency is the reason we exist otherwise [pepperoni](https://github.com/futurice/pepperoni-app-kit/) wouldn't have existed. Also, when I try to find meaning on google, first two results are links two issues and rest are links to readme of libraries using this word.
