### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by matejstrasek** [futurice/pepperoni-app-kit#205]
There is no more activity in this project since April 4th. 

Was the project deprecated?

**Comment by mdcuk34** [comment]
+1

**Comment by FruitieX** [comment]
Hi, I suppose our maintainers have been very busy with customer projects. I will attempt to take the ball on this in about 2 weeks from now and give the project some work it desperately needs.

**Comment by lucidlemon** [comment]
So the attempt on taking the ball was closing this issue? :) seems like the project is pretty dead which is a shame - it's by far the best starter for react-native apps, would be lovely to see you guys pick this up, or at least write some basic documentation in terms of a small page.

For example like how to reset the state in order to fix #225

**Comment by FruitieX** [comment]
Totally WIP https://github.com/futurice/pepperoni-crna :)
