### ISSUE TITLE
Alternative Router

### ISSUE THREAD

**Issue by bennythomps** [futurice/pepperoni-app-kit#30]
I'm sure it was intentional, so if nothing else, just curiosity. Why the choice to use a custom router instead of something like react-native-router-flux?

**Comment by jevakallio** [comment]
@bennythomps thanks for asking this question. I want to document this rationale in our architecture documentation, but here's a quick overview:

We have used `react-native-router-flux` in a previous app, and we did not find it a good solution. Despite its name, it doesn't allow you to easily and cleanly to control the navigation state using a single, declarative application state managed by Flux/Redux. This is not entirely that library's fault. Internally `react-native-router-flux` uses `ExNavigator`, which in turn uses the standard React Native `Navigator`, which is inherently stateful and can not act as a controlled component.

That said, `react-native-router-flux` is not a great quality component. The documentation seems to be perpetually out of date, and we've encountered hard-to-track bugs while developing apps with it. For developers who want to use the traditional `Navigator` component, I recommend going one level deeper and using [ExNavigator](https://github.com/exponentjs/ex-navigator) directly - it's simple, and works great!

Instead of using `ExNavigator`, as we have in the past, we opted to using the new `NavigationExperimental` API provided by React Native itself for two reasons:

 1. `NavigationExperimental` allows us to control the navigation state from Redux. This makes it possible to persist the applicatioon navigation state as part of the app state, cause navigation transitions as controlled `redux-loop` effects, and a number of other benefits.
 2. `NavigationExperimental` is the future of React Native navigation. Pepperoni is a boilerplate for the future, and we wanted to be forward-looking in our choices. The API is changing a lot though, and there will be some significant changes as we upgrade to RN 0.28.

The "Router" component we have in place in Pepperoni is not a permanent structure. We opted for the simplest possible solution as a starting point, and fully expect app developers to have to extend or refactor it as their apps grow. Not building a heavy abstraction has turned out to be a good, as RN 0.28 will remove the route `key` property which is currently being used for view mapping, and we will need to find another solution.

As the `NavigationExperimental` component becomes the default API, the community (or maybe us!) will come up with a more sophisticated Router, which we will gladly use. But there isn't one yet.

Hope this anwers your question!
