### ISSUE TITLE
snapshot.rehydrate does not restore arrays properly

### ISSUE THREAD

**Issue by emmby** [futurice/pepperoni-app-kit#48]
They're VNodes instead of arrays, so components expecting arrays in props will crash.

**Comment by jevakallio** [comment]
@emmby thanks for reporting this. The state rehydration converts the entire state map to an Immutable.js data structures, in case of arrays to `List`. The VNodes you are seeing are `List` nodes in a Immutable `Map`.

This is intentional, as in the Pepperoni architecture the entire state of your application should be an immutable data structure to begin with - i.e. you should never have plain javascript objects or arrays in your application state. For the rationale behind immutable app architectures, I recommend watching [Lee Byron's talk about them](https://vimeo.com/166790294).

I admit the documentation does not make this clear. I will improve the documentation, tracked by https://github.com/futurice/pepperoni-app-kit/issues/49.
