### ISSUE TITLE
How to replace Auth0

### ISSUE THREAD

**Issue by michaelswe** [futurice/pepperoni-app-kit#78]
Auth0 seems to have its own modal forms for authentication. I want to use my own authentication on my own server and I want to build the forms myself.
1.  How would be the best way to get rid of Auth0. I'm worried that if I tamper too much with the code I'll have an even harder time when I want to cherry pick/merge newer pepperoni versions.
2. I want my login screens (signin/signup/reset/etc) at the root of the navigation. But I also want to use tabs in the main screen. How would be a good way to implement this? 

Would the following make sense?
I'll have two roots. I.e. at initialization I'll just have my login route in the navigationState, but after a successful authentication I would force a new "initialState" upon the navigator. Also, a logout would clear the navigation state again and reinstate the initial login route.

Thanks.

**Comment by michaelswe** [comment]
I'm experimenting with the above idea but got into trouble.

Here is what I did to the NavigationState:

    const mainRootState = fromJS(
      createNavigationState('MainNavigation', 'App', [
        createNavigationState('HomeTab', 'Home', [{key: 'Counter', title: 'Counter'}]),
        createNavigationState('ProfileTab', 'Project', [{key: 'Counter', title: 'Project'}]),
        createNavigationState('TestTab', 'Test', [{key: 'Counter', title: 'Test'}])
      ]));
     
    const authenticationRootState = fromJS(
      createNavigationState('Login', 'Login', [{key: 'Login', title: 'Login'}]),
    );
  
    export default function NavigationReducer(state = authenticationRootState, action) {
      switch (action.type) {
        case AUTHENTICATION_ROOT:
          return authenticationRootState
            .set('isNavigating', true);
  
        case MAIN_ROOT:
          return mainRootState
            .set('isNavigating', true);
  
        case PUSH_ROUTE:
          return state
            .set('isNavigating', true)
            .updateIn(['routes', state.get('index')], tabState =>
              tabState
                .update('routes', routes => routes.push(fromJS(action.payload)))
    .
    .
    .


But the new "authenticationRootState" won't render well in the NavigationView. Should I alter the NavigationView to cope with my non-tabs-route, or should I build a secondary NavigationView just for the login handling, i.e. "LoginNavigationView".

As you see I'm new to this. I'll probably figure out some sort of hacky solution, but I'd really appreciate some input. I suppose there are others than me who don't want to use Auth0..

**Comment by folivi** [comment]
Furthermore, Auth0 is according to me too expensive.
The starter kit is great but orienting developers to use AUth0 is quiet a downside

**Comment by monotv** [comment]
Moving this into some kind of abstraction layer where I can implement whatever auth method/backend I want to use would be great.

**Comment by ndbroadbent** [comment]
Yeah, that was the first thing I noticed, and really puts me off using this starter kit. I don't want to have to rip out the authentication and write my own from scratch, even though it should only take a couple of days. We all want to have 100,000 monthly active users, and none of us want to pay $1,577 per month just for some authentication that we could easily build ourselves.

Would you be in favor of removing Auth0 if some of us contributed the code to replace it?

**Comment by jevakallio** [comment]
Hi @ndbroadbent @monotv I have opened an issue to remove Auth0 as a default dependency at https://github.com/futurice/pepperoni-app-kit/issues/96. We still want to use Auth0 in internal Futurice projects that use Pepperoni, and want to make using it as simple as possible, but in hindsight it's obvious that this opinionated feature was a little too opinionated.

In the meantime, please check out https://github.com/futurice/pepperoni-app-kit/issues/92#issuecomment-238091047 for some initial notes on how to implement custom JWT authentication using pre-existing Pepperoni `authentication` and `api` modules.

As to accepting a custom-developed login functionality, I'm afraid whatever solution we make would be too opinionated in the same way as Auth0 has turned out to be. The custom login flow should rather be implemented as a separate npm module without dependency to Pepperoni. If someone ends up implementing this (and if it's any good :) we'll gladly link to it from the Pepperoni documentation.

Thank you for the valuable feedback :bow:

**Comment by infacq** [comment]
look forward

**Comment by wandonye** [comment]
Half of my app users are expected from China, so Auth0 doesn't really work for my need. So this feature will be really helpful for us

**Comment by tino-junge** [comment]
Closing this issue now since we've now made Auth0 optional for pepperoni :)

**Comment by puzpuz** [comment]
@wandonye  Hi, care to share what Authentication service did you use for user in China? Thank you :)
